using Mci.Core.Domain.Enums;

namespace Mci.Infrastructure.Persistence.Seeding;

public static class MciReferenceData
{
    public static readonly DateTime SeededAtUtc = new(2026, 7, 5, 0, 0, 0, DateTimeKind.Utc);

    public static readonly object[] Counties =
    [
        County(1, "26001", "Alcona"),
        County(2, "26003", "Alger"),
        County(3, "26005", "Allegan"),
        County(4, "26007", "Alpena"),
        County(5, "26009", "Antrim"),
        County(6, "26011", "Arenac"),
        County(7, "26013", "Baraga"),
        County(8, "26015", "Barry"),
        County(9, "26017", "Bay"),
        County(10, "26019", "Benzie"),
        County(11, "26021", "Berrien"),
        County(12, "26023", "Branch"),
        County(13, "26025", "Calhoun"),
        County(14, "26027", "Cass"),
        County(15, "26029", "Charlevoix"),
        County(16, "26031", "Cheboygan"),
        County(17, "26033", "Chippewa"),
        County(18, "26035", "Clare"),
        County(19, "26037", "Clinton"),
        County(20, "26039", "Crawford"),
        County(21, "26041", "Delta"),
        County(22, "26043", "Dickinson"),
        County(23, "26045", "Eaton"),
        County(24, "26047", "Emmet"),
        County(25, "26049", "Genesee"),
        County(26, "26051", "Gladwin"),
        County(27, "26053", "Gogebic"),
        County(28, "26055", "Grand Traverse"),
        County(29, "26057", "Gratiot"),
        County(30, "26059", "Hillsdale"),
        County(31, "26061", "Houghton"),
        County(32, "26063", "Huron"),
        County(33, "26065", "Ingham"),
        County(34, "26067", "Ionia"),
        County(35, "26069", "Iosco"),
        County(36, "26071", "Iron"),
        County(37, "26073", "Isabella"),
        County(38, "26075", "Jackson"),
        County(39, "26077", "Kalamazoo"),
        County(40, "26079", "Kalkaska"),
        County(41, "26081", "Kent"),
        County(42, "26083", "Keweenaw"),
        County(43, "26085", "Lake"),
        County(44, "26087", "Lapeer"),
        County(45, "26089", "Leelanau"),
        County(46, "26091", "Lenawee"),
        County(47, "26093", "Livingston"),
        County(48, "26095", "Luce"),
        County(49, "26097", "Mackinac"),
        County(50, "26099", "Macomb"),
        County(51, "26101", "Manistee"),
        County(52, "26103", "Marquette"),
        County(53, "26105", "Mason"),
        County(54, "26107", "Mecosta"),
        County(55, "26109", "Menominee"),
        County(56, "26111", "Midland"),
        County(57, "26113", "Missaukee"),
        County(58, "26115", "Monroe"),
        County(59, "26117", "Montcalm"),
        County(60, "26119", "Montmorency"),
        County(61, "26121", "Muskegon"),
        County(62, "26123", "Newaygo"),
        County(63, "26125", "Oakland"),
        County(64, "26127", "Oceana"),
        County(65, "26129", "Ogemaw"),
        County(66, "26131", "Ontonagon"),
        County(67, "26133", "Osceola"),
        County(68, "26135", "Oscoda"),
        County(69, "26137", "Otsego"),
        County(70, "26139", "Ottawa"),
        County(71, "26141", "Presque Isle"),
        County(72, "26143", "Roscommon"),
        County(73, "26145", "Saginaw"),
        County(74, "26147", "St. Clair"),
        County(75, "26149", "St. Joseph"),
        County(76, "26151", "Sanilac"),
        County(77, "26153", "Schoolcraft"),
        County(78, "26155", "Shiawassee"),
        County(79, "26157", "Tuscola"),
        County(80, "26159", "Van Buren"),
        County(81, "26161", "Washtenaw"),
        County(82, "26163", "Wayne"),
        County(83, "26165", "Wexford")
    ];

    public static readonly object[] MetricDefinitions =
    [
        Metric(
            1,
            "population",
            "Population",
            "Total population estimate for the county.",
            "Demographics",
            MetricUnit.Count,
            0,
            MetricCalculationType.DirectSource,
            "Show as a rolling ACS 5-Year estimate. Do not label adjacent release changes as year-over-year growth.",
            false,
            false),
        Metric(
            2,
            "median_household_income",
            "Median Household Income",
            "Median household income in the past 12 months, reported by ACS.",
            "Economy",
            MetricUnit.Currency,
            0,
            MetricCalculationType.DirectSource,
            "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
            true,
            false),
        Metric(
            3,
            "per_capita_income",
            "Per Capita Income",
            "Per capita income in the past 12 months, reported by ACS.",
            "Economy",
            MetricUnit.Currency,
            0,
            MetricCalculationType.DirectSource,
            "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
            true,
            false),
        Metric(
            4,
            "poverty_rate",
            "Poverty Rate",
            "Share of the population for whom poverty status is determined that is below the poverty level.",
            "Economy",
            MetricUnit.Percentage,
            1,
            MetricCalculationType.Derived,
            "Compare counties within the same ACS release. Use non-overlapping periods for change comparisons.",
            false,
            false),
        Metric(
            5,
            "labor_force_participation_rate",
            "Labor Force Participation Rate",
            "Share of the civilian population age 16 and over that is in the labor force.",
            "Economy",
            MetricUnit.Percentage,
            1,
            MetricCalculationType.Derived,
            "Compare counties within the same ACS release. Use non-overlapping periods for change comparisons.",
            false,
            false),
        Metric(
            6,
            "bachelors_degree_or_higher_rate",
            "Bachelor's Degree or Higher",
            "Share of the population age 25 and over with a bachelor's, master's, professional, or doctorate degree.",
            "Education",
            MetricUnit.Percentage,
            1,
            MetricCalculationType.Derived,
            "Compare counties within the same ACS release. Use non-overlapping periods for change comparisons.",
            false,
            false),
        Metric(
            7,
            "median_home_value",
            "Median Home Value",
            "Median value of owner-occupied housing units.",
            "Housing",
            MetricUnit.Currency,
            0,
            MetricCalculationType.DirectSource,
            "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
            true,
            false),
        Metric(
            8,
            "median_gross_rent",
            "Median Gross Rent",
            "Median gross rent for renter-occupied housing units paying cash rent.",
            "Housing",
            MetricUnit.Currency,
            0,
            MetricCalculationType.DirectSource,
            "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
            true,
            false)
    ];

    public static readonly object[] DataReleases =
    [
        new
        {
            Id = 1,
            SourceCode = "CENSUS",
            DatasetCode = "ACS5_DETAILED",
            ReleaseYear = (short)2024,
            PeriodStartYear = (short)2020,
            PeriodEndYear = (short)2024,
            DisplayName = "2020-2024 ACS 5-Year",
            IsDefault = true,
            CreatedAtUtc = SeededAtUtc
        }
    ];

    private static object County(int id, string fipsCode, string name) => new
    {
        Id = id,
        FipsCode = fipsCode,
        Name = name,
        StateFipsCode = "26",
        StateCode = "MI",
        StateName = "Michigan",
        IsActive = true,
        CreatedAtUtc = SeededAtUtc,
        UpdatedAtUtc = SeededAtUtc
    };

    private static object Metric(
        int id,
        string code,
        string displayName,
        string description,
        string category,
        MetricUnit unit,
        byte decimalPlaces,
        MetricCalculationType calculationType,
        string comparisonGuidance,
        bool requiresDollarNormalization,
        bool supportsAdjacentReleaseComparison) => new
    {
        Id = id,
        Code = code,
        DisplayName = displayName,
        Description = description,
        Category = category,
        Unit = unit,
        DecimalPlaces = decimalPlaces,
        CalculationType = calculationType,
        ComparisonGuidance = comparisonGuidance,
        RequiresDollarNormalization = requiresDollarNormalization,
        SupportsAdjacentReleaseComparison = supportsAdjacentReleaseComparison,
        IsActive = true,
        CreatedAtUtc = SeededAtUtc
    };
}
