// <auto-generated />
using System;
using Mci.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mci.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MciDbContext))]
    [Migration("20260705120909_Seed2024AcsDataRelease")]
    partial class Seed2024AcsDataRelease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mci.Core.Domain.Entities.AcsCountyVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnnotationRaw")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CountyFipsCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<string>("CountyNameRaw")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EstimateRaw")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MarginOfErrorRaw")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceRowHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("SourceVariableCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("StagedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "CountyFipsCode", "SourceVariableCode")
                        .IsUnique();

                    b.ToTable("AcsCountyVariable", "mci_stg");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FipsCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("StateFipsCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("FipsCode")
                        .IsUnique();

                    b.ToTable("County", "mci_ref", t =>
                        {
                            t.HasCheckConstraint("CK_County_FipsCode_Length", "LEN([FipsCode]) = 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26001",
                            IsActive = true,
                            Name = "Alcona",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26003",
                            IsActive = true,
                            Name = "Alger",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26005",
                            IsActive = true,
                            Name = "Allegan",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26007",
                            IsActive = true,
                            Name = "Alpena",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26009",
                            IsActive = true,
                            Name = "Antrim",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26011",
                            IsActive = true,
                            Name = "Arenac",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26013",
                            IsActive = true,
                            Name = "Baraga",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26015",
                            IsActive = true,
                            Name = "Barry",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26017",
                            IsActive = true,
                            Name = "Bay",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26019",
                            IsActive = true,
                            Name = "Benzie",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26021",
                            IsActive = true,
                            Name = "Berrien",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26023",
                            IsActive = true,
                            Name = "Branch",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26025",
                            IsActive = true,
                            Name = "Calhoun",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26027",
                            IsActive = true,
                            Name = "Cass",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26029",
                            IsActive = true,
                            Name = "Charlevoix",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26031",
                            IsActive = true,
                            Name = "Cheboygan",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26033",
                            IsActive = true,
                            Name = "Chippewa",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26035",
                            IsActive = true,
                            Name = "Clare",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26037",
                            IsActive = true,
                            Name = "Clinton",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26039",
                            IsActive = true,
                            Name = "Crawford",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26041",
                            IsActive = true,
                            Name = "Delta",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26043",
                            IsActive = true,
                            Name = "Dickinson",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26045",
                            IsActive = true,
                            Name = "Eaton",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26047",
                            IsActive = true,
                            Name = "Emmet",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26049",
                            IsActive = true,
                            Name = "Genesee",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26051",
                            IsActive = true,
                            Name = "Gladwin",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26053",
                            IsActive = true,
                            Name = "Gogebic",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26055",
                            IsActive = true,
                            Name = "Grand Traverse",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26057",
                            IsActive = true,
                            Name = "Gratiot",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26059",
                            IsActive = true,
                            Name = "Hillsdale",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26061",
                            IsActive = true,
                            Name = "Houghton",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26063",
                            IsActive = true,
                            Name = "Huron",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26065",
                            IsActive = true,
                            Name = "Ingham",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26067",
                            IsActive = true,
                            Name = "Ionia",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26069",
                            IsActive = true,
                            Name = "Iosco",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26071",
                            IsActive = true,
                            Name = "Iron",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26073",
                            IsActive = true,
                            Name = "Isabella",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26075",
                            IsActive = true,
                            Name = "Jackson",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26077",
                            IsActive = true,
                            Name = "Kalamazoo",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26079",
                            IsActive = true,
                            Name = "Kalkaska",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26081",
                            IsActive = true,
                            Name = "Kent",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26083",
                            IsActive = true,
                            Name = "Keweenaw",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26085",
                            IsActive = true,
                            Name = "Lake",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26087",
                            IsActive = true,
                            Name = "Lapeer",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26089",
                            IsActive = true,
                            Name = "Leelanau",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26091",
                            IsActive = true,
                            Name = "Lenawee",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26093",
                            IsActive = true,
                            Name = "Livingston",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26095",
                            IsActive = true,
                            Name = "Luce",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26097",
                            IsActive = true,
                            Name = "Mackinac",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26099",
                            IsActive = true,
                            Name = "Macomb",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26101",
                            IsActive = true,
                            Name = "Manistee",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26103",
                            IsActive = true,
                            Name = "Marquette",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26105",
                            IsActive = true,
                            Name = "Mason",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 54,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26107",
                            IsActive = true,
                            Name = "Mecosta",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 55,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26109",
                            IsActive = true,
                            Name = "Menominee",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 56,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26111",
                            IsActive = true,
                            Name = "Midland",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 57,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26113",
                            IsActive = true,
                            Name = "Missaukee",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 58,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26115",
                            IsActive = true,
                            Name = "Monroe",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 59,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26117",
                            IsActive = true,
                            Name = "Montcalm",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 60,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26119",
                            IsActive = true,
                            Name = "Montmorency",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 61,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26121",
                            IsActive = true,
                            Name = "Muskegon",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 62,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26123",
                            IsActive = true,
                            Name = "Newaygo",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 63,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26125",
                            IsActive = true,
                            Name = "Oakland",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 64,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26127",
                            IsActive = true,
                            Name = "Oceana",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 65,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26129",
                            IsActive = true,
                            Name = "Ogemaw",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 66,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26131",
                            IsActive = true,
                            Name = "Ontonagon",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 67,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26133",
                            IsActive = true,
                            Name = "Osceola",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 68,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26135",
                            IsActive = true,
                            Name = "Oscoda",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 69,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26137",
                            IsActive = true,
                            Name = "Otsego",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26139",
                            IsActive = true,
                            Name = "Ottawa",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 71,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26141",
                            IsActive = true,
                            Name = "Presque Isle",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 72,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26143",
                            IsActive = true,
                            Name = "Roscommon",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 73,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26145",
                            IsActive = true,
                            Name = "Saginaw",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 74,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26147",
                            IsActive = true,
                            Name = "St. Clair",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 75,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26149",
                            IsActive = true,
                            Name = "St. Joseph",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 76,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26151",
                            IsActive = true,
                            Name = "Sanilac",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 77,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26153",
                            IsActive = true,
                            Name = "Schoolcraft",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 78,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26155",
                            IsActive = true,
                            Name = "Shiawassee",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 79,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26157",
                            IsActive = true,
                            Name = "Tuscola",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 80,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26159",
                            IsActive = true,
                            Name = "Van Buren",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 81,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26161",
                            IsActive = true,
                            Name = "Washtenaw",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 82,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26163",
                            IsActive = true,
                            Name = "Wayne",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 83,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FipsCode = "26165",
                            IsActive = true,
                            Name = "Wexford",
                            StateCode = "MI",
                            StateFipsCode = "26",
                            StateName = "Michigan",
                            UpdatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.CountyMetricObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DataReleaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimateValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MarginOfError")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("MetricDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataReleaseId", "ImportRunId");

                    b.HasIndex("CountyId", "MetricDefinitionId", "DataReleaseId");

                    b.HasIndex("ImportRunId", "CountyId", "MetricDefinitionId")
                        .IsUnique();

                    b.HasIndex("MetricDefinitionId", "DataReleaseId", "EstimateValue");

                    b.ToTable("CountyMetricObservation", "mci_fact", t =>
                        {
                            t.HasCheckConstraint("CK_CountyMetricObservation_MarginOfError", "[MarginOfError] IS NULL OR [MarginOfError] >= 0");
                        });
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.CurrentCountyMetricObservation", b =>
                {
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountyFipsCode")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataReleaseDisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DataReleaseId")
                        .HasColumnType("int");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("EstimateValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MarginOfError")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MetricDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("MetricDisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("ObservationId")
                        .HasColumnType("bigint");

                    b.Property<short>("PeriodEndYear")
                        .HasColumnType("smallint");

                    b.Property<short>("PeriodStartYear")
                        .HasColumnType("smallint");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable((string)null);

                    b.ToView("vw_CurrentCountyMetricObservation", "mci_reporting");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.DataRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DatasetCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<short>("PeriodEndYear")
                        .HasColumnType("smallint");

                    b.Property<short>("PeriodStartYear")
                        .HasColumnType("smallint");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SourceCode", "DatasetCode")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("SourceCode", "DatasetCode", "ReleaseYear")
                        .IsUnique();

                    b.ToTable("DataRelease", "mci_ops", t =>
                        {
                            t.HasCheckConstraint("CK_DataRelease_Period", "[PeriodStartYear] <= [PeriodEndYear] AND [PeriodEndYear] = [ReleaseYear]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatasetCode = "ACS5_DETAILED",
                            DisplayName = "2020-2024 ACS 5-Year",
                            IsDefault = true,
                            PeriodEndYear = (short)2024,
                            PeriodStartYear = (short)2020,
                            ReleaseYear = (short)2024,
                            SourceCode = "CENSUS"
                        });
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.ImportIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CountyFipsCode")
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IssueCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MetricCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Severity", "Stage");

                    b.ToTable("ImportIssue", "mci_ops");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DataReleaseId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RecordsFetched")
                        .HasColumnType("int");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("int");

                    b.Property<int>("RecordsStaged")
                        .HasColumnType("int");

                    b.Property<Guid?>("RetryOfImportRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("RetryOfImportRunId");

                    b.HasIndex("DataReleaseId", "Status", "CompletedAtUtc");

                    b.ToTable("ImportRun", "mci_ops", t =>
                        {
                            t.HasCheckConstraint("CK_ImportRun_Completion", "([Status] IN ('Queued', 'Running') AND [CompletedAtUtc] IS NULL) OR ([Status] IN ('Succeeded', 'SucceededWithWarnings', 'Failed') AND [CompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ImportRun_RecordCounts", "[RecordsFetched] >= 0 AND [RecordsStaged] >= 0 AND [RecordsInserted] >= 0 AND [RecordsRejected] >= 0");
                        });
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.MetricDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ComparisonGuidance")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresDollarNormalization")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsAdjacentReleaseComparison")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MetricDefinition", "mci_catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationType = "DirectSource",
                            Category = "Demographics",
                            Code = "population",
                            ComparisonGuidance = "Show as a rolling ACS 5-Year estimate. Do not label adjacent release changes as year-over-year growth.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)0,
                            Description = "Total population estimate for the county.",
                            DisplayName = "Population",
                            IsActive = true,
                            RequiresDollarNormalization = false,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Count"
                        },
                        new
                        {
                            Id = 2,
                            CalculationType = "DirectSource",
                            Category = "Economy",
                            Code = "median_household_income",
                            ComparisonGuidance = "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)0,
                            Description = "Median household income in the past 12 months, reported by ACS.",
                            DisplayName = "Median Household Income",
                            IsActive = true,
                            RequiresDollarNormalization = true,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Currency"
                        },
                        new
                        {
                            Id = 3,
                            CalculationType = "DirectSource",
                            Category = "Economy",
                            Code = "per_capita_income",
                            ComparisonGuidance = "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)0,
                            Description = "Per capita income in the past 12 months, reported by ACS.",
                            DisplayName = "Per Capita Income",
                            IsActive = true,
                            RequiresDollarNormalization = true,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Currency"
                        },
                        new
                        {
                            Id = 4,
                            CalculationType = "Derived",
                            Category = "Economy",
                            Code = "poverty_rate",
                            ComparisonGuidance = "Compare counties within the same ACS release. Use non-overlapping periods for change comparisons.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)1,
                            Description = "Share of the population for whom poverty status is determined that is below the poverty level.",
                            DisplayName = "Poverty Rate",
                            IsActive = true,
                            RequiresDollarNormalization = false,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Percentage"
                        },
                        new
                        {
                            Id = 5,
                            CalculationType = "Derived",
                            Category = "Economy",
                            Code = "labor_force_participation_rate",
                            ComparisonGuidance = "Compare counties within the same ACS release. Use non-overlapping periods for change comparisons.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)1,
                            Description = "Share of the civilian population age 16 and over that is in the labor force.",
                            DisplayName = "Labor Force Participation Rate",
                            IsActive = true,
                            RequiresDollarNormalization = false,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Percentage"
                        },
                        new
                        {
                            Id = 6,
                            CalculationType = "Derived",
                            Category = "Education",
                            Code = "bachelors_degree_or_higher_rate",
                            ComparisonGuidance = "Compare counties within the same ACS release. Use non-overlapping periods for change comparisons.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)1,
                            Description = "Share of the population age 25 and over with a bachelor's, master's, professional, or doctorate degree.",
                            DisplayName = "Bachelor's Degree or Higher",
                            IsActive = true,
                            RequiresDollarNormalization = false,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Percentage"
                        },
                        new
                        {
                            Id = 7,
                            CalculationType = "DirectSource",
                            Category = "Housing",
                            Code = "median_home_value",
                            ComparisonGuidance = "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)0,
                            Description = "Median value of owner-occupied housing units.",
                            DisplayName = "Median Home Value",
                            IsActive = true,
                            RequiresDollarNormalization = true,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Currency"
                        },
                        new
                        {
                            Id = 8,
                            CalculationType = "DirectSource",
                            Category = "Housing",
                            Code = "median_gross_rent",
                            ComparisonGuidance = "Show release periods clearly. Cross-period dollar comparisons are not inflation-adjusted in V1.",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = (byte)0,
                            Description = "Median gross rent for renter-occupied housing units paying cash rent.",
                            DisplayName = "Median Gross Rent",
                            IsActive = true,
                            RequiresDollarNormalization = true,
                            SupportsAdjacentReleaseComparison = false,
                            Unit = "Currency"
                        });
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.AcsCountyVariable", b =>
                {
                    b.HasOne("Mci.Core.Domain.Entities.ImportRun", "ImportRun")
                        .WithMany("AcsCountyVariables")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.CountyMetricObservation", b =>
                {
                    b.HasOne("Mci.Core.Domain.Entities.County", "County")
                        .WithMany("Observations")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mci.Core.Domain.Entities.DataRelease", "DataRelease")
                        .WithMany("Observations")
                        .HasForeignKey("DataReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mci.Core.Domain.Entities.MetricDefinition", "MetricDefinition")
                        .WithMany("Observations")
                        .HasForeignKey("MetricDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mci.Core.Domain.Entities.ImportRun", "ImportRun")
                        .WithMany("Observations")
                        .HasForeignKey("DataReleaseId", "ImportRunId")
                        .HasPrincipalKey("DataReleaseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("County");

                    b.Navigation("DataRelease");

                    b.Navigation("ImportRun");

                    b.Navigation("MetricDefinition");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.ImportIssue", b =>
                {
                    b.HasOne("Mci.Core.Domain.Entities.ImportRun", "ImportRun")
                        .WithMany("ImportIssues")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.ImportRun", b =>
                {
                    b.HasOne("Mci.Core.Domain.Entities.DataRelease", "DataRelease")
                        .WithMany("ImportRuns")
                        .HasForeignKey("DataReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mci.Core.Domain.Entities.ImportRun", "RetryOfImportRun")
                        .WithMany()
                        .HasForeignKey("RetryOfImportRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DataRelease");

                    b.Navigation("RetryOfImportRun");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.County", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.DataRelease", b =>
                {
                    b.Navigation("ImportRuns");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.ImportRun", b =>
                {
                    b.Navigation("AcsCountyVariables");

                    b.Navigation("ImportIssues");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Mci.Core.Domain.Entities.MetricDefinition", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
